// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/alandtsang/gormgen/dal/model"
)

func newContactGroups(db *gorm.DB) contactGroups {
	_contactGroups := contactGroups{}

	_contactGroups.contactGroupsDo.UseDB(db)
	_contactGroups.contactGroupsDo.UseModel(&model.ContactGroups{})

	tableName := _contactGroups.contactGroupsDo.TableName()
	_contactGroups.ALL = field.NewField(tableName, "*")
	_contactGroups.ID = field.NewInt(tableName, "id")
	_contactGroups.Name = field.NewString(tableName, "name")
	_contactGroups.Remarks = field.NewString(tableName, "remarks")
	_contactGroups.CreatedAt = field.NewTime(tableName, "created_at")
	_contactGroups.UpdatedAt = field.NewTime(tableName, "updated_at")

	_contactGroups.fillFieldMap()

	return _contactGroups
}

type contactGroups struct {
	contactGroupsDo contactGroupsDo

	ALL       field.Field
	ID        field.Int
	Name      field.String
	Remarks   field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c contactGroups) Table(newTableName string) *contactGroups {
	c.contactGroupsDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contactGroups) As(alias string) *contactGroups {
	c.contactGroupsDo.DO = *(c.contactGroupsDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contactGroups) updateTableName(table string) *contactGroups {
	c.ALL = field.NewField(table, "*")
	c.ID = field.NewInt(table, "id")
	c.Name = field.NewString(table, "name")
	c.Remarks = field.NewString(table, "remarks")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *contactGroups) WithContext(ctx context.Context) *contactGroupsDo {
	return c.contactGroupsDo.WithContext(ctx)
}

func (c contactGroups) TableName() string { return c.contactGroupsDo.TableName() }

func (c contactGroups) Alias() string { return c.contactGroupsDo.Alias() }

func (c *contactGroups) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contactGroups) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["remarks"] = c.Remarks
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c contactGroups) clone(db *gorm.DB) contactGroups {
	c.contactGroupsDo.ReplaceDB(db)
	return c
}

type contactGroupsDo struct{ gen.DO }

func (c contactGroupsDo) Debug() *contactGroupsDo {
	return c.withDO(c.DO.Debug())
}

func (c contactGroupsDo) WithContext(ctx context.Context) *contactGroupsDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contactGroupsDo) Clauses(conds ...clause.Expression) *contactGroupsDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contactGroupsDo) Returning(value interface{}, columns ...string) *contactGroupsDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contactGroupsDo) Not(conds ...gen.Condition) *contactGroupsDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contactGroupsDo) Or(conds ...gen.Condition) *contactGroupsDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contactGroupsDo) Select(conds ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contactGroupsDo) Where(conds ...gen.Condition) *contactGroupsDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contactGroupsDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *contactGroupsDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c contactGroupsDo) Order(conds ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contactGroupsDo) Distinct(cols ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contactGroupsDo) Omit(cols ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contactGroupsDo) Join(table schema.Tabler, on ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contactGroupsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contactGroupsDo) RightJoin(table schema.Tabler, on ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contactGroupsDo) Group(cols ...field.Expr) *contactGroupsDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contactGroupsDo) Having(conds ...gen.Condition) *contactGroupsDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contactGroupsDo) Limit(limit int) *contactGroupsDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contactGroupsDo) Offset(offset int) *contactGroupsDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contactGroupsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contactGroupsDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contactGroupsDo) Unscoped() *contactGroupsDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contactGroupsDo) Create(values ...*model.ContactGroups) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contactGroupsDo) CreateInBatches(values []*model.ContactGroups, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contactGroupsDo) Save(values ...*model.ContactGroups) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contactGroupsDo) First() (*model.ContactGroups, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactGroups), nil
	}
}

func (c contactGroupsDo) Take() (*model.ContactGroups, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactGroups), nil
	}
}

func (c contactGroupsDo) Last() (*model.ContactGroups, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactGroups), nil
	}
}

func (c contactGroupsDo) Find() ([]*model.ContactGroups, error) {
	result, err := c.DO.Find()
	return result.([]*model.ContactGroups), err
}

func (c contactGroupsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContactGroups, err error) {
	buf := make([]*model.ContactGroups, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contactGroupsDo) FindInBatches(result *[]*model.ContactGroups, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contactGroupsDo) Attrs(attrs ...field.AssignExpr) *contactGroupsDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contactGroupsDo) Assign(attrs ...field.AssignExpr) *contactGroupsDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contactGroupsDo) Joins(fields ...field.RelationField) *contactGroupsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contactGroupsDo) Preload(fields ...field.RelationField) *contactGroupsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contactGroupsDo) FirstOrInit() (*model.ContactGroups, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactGroups), nil
	}
}

func (c contactGroupsDo) FirstOrCreate() (*model.ContactGroups, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactGroups), nil
	}
}

func (c contactGroupsDo) FindByPage(offset int, limit int) (result []*model.ContactGroups, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contactGroupsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c *contactGroupsDo) withDO(do gen.Dao) *contactGroupsDo {
	c.DO = *do.(*gen.DO)
	return c
}
